Traceback (most recent call last):
  File "./lab1.pytorch", line 114, in <module>
    (t1,t2) = train(epoch,500,agg_io_time,agg_pre_time)
  File "./lab1.pytorch", line 92, in train
    for batch_idx, (tio,tpre,data, target) in enumerate(train_loader):
  File "/share/apps/pytorch/0.3.0_4/python3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 310, in __iter__
    return DataLoaderIter(self)
  File "/share/apps/pytorch/0.3.0_4/python3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 150, in __init__
    if self.num_workers > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
Exception ignored in: <bound method DataLoaderIter.__del__ of <torch.utils.data.dataloader.DataLoaderIter object at 0x2abc5fc2ad68>>
Traceback (most recent call last):
  File "/share/apps/pytorch/0.3.0_4/python3.6/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 249, in __del__
    if self.num_workers > 0:
TypeError: '>' not supported between instances of 'str' and 'int'
